//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthGuardApp.ServiceReference4 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WCFHealthGuard")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference4.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/userRegister", ReplyAction="http://tempuri.org/IService1/userRegisterResponse")]
        void userRegister(string login, string password, string password2, string name, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/userRegister", ReplyAction="http://tempuri.org/IService1/userRegisterResponse")]
        System.Threading.Tasks.Task userRegisterAsync(string login, string password, string password2, string name, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getprofileID", ReplyAction="http://tempuri.org/IService1/getprofileIDResponse")]
        int getprofileID(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getprofileID", ReplyAction="http://tempuri.org/IService1/getprofileIDResponse")]
        System.Threading.Tasks.Task<int> getprofileIDAsync(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getPatientInformation", ReplyAction="http://tempuri.org/IService1/getPatientInformationResponse")]
        HealthGuardObjects.user getPatientInformation(int login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getPatientInformation", ReplyAction="http://tempuri.org/IService1/getPatientInformationResponse")]
        System.Threading.Tasks.Task<HealthGuardObjects.user> getPatientInformationAsync(int login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertingtheData", ReplyAction="http://tempuri.org/IService1/InsertingtheDataResponse")]
        void InsertingtheData(string login, string password, string password2, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertingtheData", ReplyAction="http://tempuri.org/IService1/InsertingtheDataResponse")]
        System.Threading.Tasks.Task InsertingtheDataAsync(string login, string password, string password2, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        HealthGuardApp.ServiceReference4.CompositeType GetDataUsingDataContract(HealthGuardApp.ServiceReference4.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<HealthGuardApp.ServiceReference4.CompositeType> GetDataUsingDataContractAsync(HealthGuardApp.ServiceReference4.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/loginUser", ReplyAction="http://tempuri.org/IService1/loginUserResponse")]
        int loginUser(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/loginUser", ReplyAction="http://tempuri.org/IService1/loginUserResponse")]
        System.Threading.Tasks.Task<int> loginUserAsync(string login, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : HealthGuardApp.ServiceReference4.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<HealthGuardApp.ServiceReference4.IService1>, HealthGuardApp.ServiceReference4.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void userRegister(string login, string password, string password2, string name, string email) {
            base.Channel.userRegister(login, password, password2, name, email);
        }
        
        public System.Threading.Tasks.Task userRegisterAsync(string login, string password, string password2, string name, string email) {
            return base.Channel.userRegisterAsync(login, password, password2, name, email);
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public int getprofileID(string login) {
            return base.Channel.getprofileID(login);
        }
        
        public System.Threading.Tasks.Task<int> getprofileIDAsync(string login) {
            return base.Channel.getprofileIDAsync(login);
        }
        
        public HealthGuardObjects.user getPatientInformation(int login) {
            return base.Channel.getPatientInformation(login);
        }
        
        public System.Threading.Tasks.Task<HealthGuardObjects.user> getPatientInformationAsync(int login) {
            return base.Channel.getPatientInformationAsync(login);
        }
        
        public void InsertingtheData(string login, string password, string password2, string name) {
            base.Channel.InsertingtheData(login, password, password2, name);
        }
        
        public System.Threading.Tasks.Task InsertingtheDataAsync(string login, string password, string password2, string name) {
            return base.Channel.InsertingtheDataAsync(login, password, password2, name);
        }
        
        public HealthGuardApp.ServiceReference4.CompositeType GetDataUsingDataContract(HealthGuardApp.ServiceReference4.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<HealthGuardApp.ServiceReference4.CompositeType> GetDataUsingDataContractAsync(HealthGuardApp.ServiceReference4.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public int loginUser(string login, string password) {
            return base.Channel.loginUser(login, password);
        }
        
        public System.Threading.Tasks.Task<int> loginUserAsync(string login, string password) {
            return base.Channel.loginUserAsync(login, password);
        }
    }
}
